<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Student extends \Entities\Student implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setStudentNumber($studentNumber)
    {
        $this->__load();
        return parent::setStudentNumber($studentNumber);
    }

    public function getStudentNumber()
    {
        $this->__load();
        return parent::getStudentNumber();
    }

    public function setFirstName($firstName)
    {
        $this->__load();
        return parent::setFirstName($firstName);
    }

    public function getFirstName()
    {
        $this->__load();
        return parent::getFirstName();
    }

    public function setSurname($surname)
    {
        $this->__load();
        return parent::setSurname($surname);
    }

    public function getSurname()
    {
        $this->__load();
        return parent::getSurname();
    }

    public function setOtherNames($otherNames)
    {
        $this->__load();
        return parent::setOtherNames($otherNames);
    }

    public function getOtherNames()
    {
        $this->__load();
        return parent::getOtherNames();
    }

    public function setDateOfBirth($dateOfBirth)
    {
        $this->__load();
        return parent::setDateOfBirth($dateOfBirth);
    }

    public function getDateOfBirth()
    {
        $this->__load();
        return parent::getDateOfBirth();
    }

    public function setGender($gender)
    {
        $this->__load();
        return parent::setGender($gender);
    }

    public function getGender()
    {
        $this->__load();
        return parent::getGender();
    }

    public function setYearEnrolled($yearEnrolled)
    {
        $this->__load();
        return parent::setYearEnrolled($yearEnrolled);
    }

    public function getYearEnrolled()
    {
        $this->__load();
        return parent::getYearEnrolled();
    }

    public function setYearCompleted($yearCompleted)
    {
        $this->__load();
        return parent::setYearCompleted($yearCompleted);
    }

    public function getYearCompleted()
    {
        $this->__load();
        return parent::getYearCompleted();
    }

    public function setTelephone($telephone)
    {
        $this->__load();
        return parent::setTelephone($telephone);
    }

    public function getTelephone()
    {
        $this->__load();
        return parent::getTelephone();
    }

    public function setAddress($address)
    {
        $this->__load();
        return parent::setAddress($address);
    }

    public function getAddress()
    {
        $this->__load();
        return parent::getAddress();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setRemarks($remarks)
    {
        $this->__load();
        return parent::setRemarks($remarks);
    }

    public function getRemarks()
    {
        $this->__load();
        return parent::getRemarks();
    }

    public function setDateCreated($dateCreated)
    {
        $this->__load();
        return parent::setDateCreated($dateCreated);
    }

    public function getDateCreated()
    {
        $this->__load();
        return parent::getDateCreated();
    }

    public function setDateLastModified($dateLastModified)
    {
        $this->__load();
        return parent::setDateLastModified($dateLastModified);
    }

    public function getDateLastModified()
    {
        $this->__load();
        return parent::getDateLastModified();
    }

    public function setIsValid($isValid)
    {
        $this->__load();
        return parent::setIsValid($isValid);
    }

    public function getIsValid()
    {
        $this->__load();
        return parent::getIsValid();
    }

    public function setAccount(\Entities\Account $account = NULL)
    {
        $this->__load();
        return parent::setAccount($account);
    }

    public function getAccount()
    {
        $this->__load();
        return parent::getAccount();
    }

    public function setHouse(\Entities\House $house = NULL)
    {
        $this->__load();
        return parent::setHouse($house);
    }

    public function getHouse()
    {
        $this->__load();
        return parent::getHouse();
    }

    public function setStudentStatus(\Entities\StudentStatus $studentStatus = NULL)
    {
        $this->__load();
        return parent::setStudentStatus($studentStatus);
    }

    public function getStudentStatus()
    {
        $this->__load();
        return parent::getStudentStatus();
    }

    public function setClassInstance(\Entities\ClassInstance $classInstance = NULL)
    {
        $this->__load();
        return parent::setClassInstance($classInstance);
    }

    public function getClassInstance()
    {
        $this->__load();
        return parent::getClassInstance();
    }

    public function setFeesProfile(\Entities\FeesProfile $feesProfile = NULL)
    {
        $this->__load();
        return parent::setFeesProfile($feesProfile);
    }

    public function getFeesProfile()
    {
        $this->__load();
        return parent::getFeesProfile();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'student_number', 'first_name', 'surname', 'other_names', 'date_of_birth', 'gender', 'year_enrolled', 'year_completed', 'telephone', 'address', 'email', 'remarks', 'date_created', 'date_last_modified', 'is_valid', 'account', 'house', 'student_status', 'class_instance', 'fees_profile');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}