<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class SchoolStaff extends \Entities\SchoolStaff implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setFirstName($firstName)
    {
        $this->__load();
        return parent::setFirstName($firstName);
    }

    public function getFirstName()
    {
        $this->__load();
        return parent::getFirstName();
    }

    public function setSurname($surname)
    {
        $this->__load();
        return parent::setSurname($surname);
    }

    public function getSurname()
    {
        $this->__load();
        return parent::getSurname();
    }

    public function setOtherNames($otherNames)
    {
        $this->__load();
        return parent::setOtherNames($otherNames);
    }

    public function getOtherNames()
    {
        $this->__load();
        return parent::getOtherNames();
    }

    public function setDateOfBirth($dateOfBirth)
    {
        $this->__load();
        return parent::setDateOfBirth($dateOfBirth);
    }

    public function getDateOfBirth()
    {
        $this->__load();
        return parent::getDateOfBirth();
    }

    public function setGender($gender)
    {
        $this->__load();
        return parent::setGender($gender);
    }

    public function getGender()
    {
        $this->__load();
        return parent::getGender();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setTelephone1($telephone1)
    {
        $this->__load();
        return parent::setTelephone1($telephone1);
    }

    public function getTelephone1()
    {
        $this->__load();
        return parent::getTelephone1();
    }

    public function setTelephone2($telephone2)
    {
        $this->__load();
        return parent::setTelephone2($telephone2);
    }

    public function getTelephone2()
    {
        $this->__load();
        return parent::getTelephone2();
    }

    public function setAddress($address)
    {
        $this->__load();
        return parent::setAddress($address);
    }

    public function getAddress()
    {
        $this->__load();
        return parent::getAddress();
    }

    public function setYearJoined($yearJoined)
    {
        $this->__load();
        return parent::setYearJoined($yearJoined);
    }

    public function getYearJoined()
    {
        $this->__load();
        return parent::getYearJoined();
    }

    public function setYearLeft($yearLeft)
    {
        $this->__load();
        return parent::setYearLeft($yearLeft);
    }

    public function getYearLeft()
    {
        $this->__load();
        return parent::getYearLeft();
    }

    public function setRemarks($remarks)
    {
        $this->__load();
        return parent::setRemarks($remarks);
    }

    public function getRemarks()
    {
        $this->__load();
        return parent::getRemarks();
    }

    public function setDateCreated($dateCreated)
    {
        $this->__load();
        return parent::setDateCreated($dateCreated);
    }

    public function getDateCreated()
    {
        $this->__load();
        return parent::getDateCreated();
    }

    public function setDateLastModified($dateLastModified)
    {
        $this->__load();
        return parent::setDateLastModified($dateLastModified);
    }

    public function getDateLastModified()
    {
        $this->__load();
        return parent::getDateLastModified();
    }

    public function setIsValid($isValid)
    {
        $this->__load();
        return parent::setIsValid($isValid);
    }

    public function getIsValid()
    {
        $this->__load();
        return parent::getIsValid();
    }

    public function setUser(\Entities\User $user = NULL)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function setJobTitle(\Entities\JobTitle $jobTitle = NULL)
    {
        $this->__load();
        return parent::setJobTitle($jobTitle);
    }

    public function getJobTitle()
    {
        $this->__load();
        return parent::getJobTitle();
    }

    public function setTitle(\Entities\Title $title = NULL)
    {
        $this->__load();
        return parent::setTitle($title);
    }

    public function getTitle()
    {
        $this->__load();
        return parent::getTitle();
    }

    public function setStaffStatus(\Entities\StaffStatus $staffStatus = NULL)
    {
        $this->__load();
        return parent::setStaffStatus($staffStatus);
    }

    public function getStaffStatus()
    {
        $this->__load();
        return parent::getStaffStatus();
    }

    public function setSystemAccountStatus(\Entities\SystemAccountStatus $systemAccountStatus = NULL)
    {
        $this->__load();
        return parent::setSystemAccountStatus($systemAccountStatus);
    }

    public function getSystemAccountStatus()
    {
        $this->__load();
        return parent::getSystemAccountStatus();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'first_name', 'surname', 'other_names', 'date_of_birth', 'gender', 'email', 'telephone1', 'telephone2', 'address', 'year_joined', 'year_left', 'remarks', 'date_created', 'date_last_modified', 'is_valid', 'user', 'job_title', 'title', 'staff_status', 'system_account_status');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}