<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class StudentFeesSummary extends \Entities\StudentFeesSummary implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setTermAmountPaid($termAmountPaid)
    {
        $this->__load();
        return parent::setTermAmountPaid($termAmountPaid);
    }

    public function getTermAmountPaid()
    {
        $this->__load();
        return parent::getTermAmountPaid();
    }

    public function setTermAmountOwed($termAmountOwed)
    {
        $this->__load();
        return parent::setTermAmountOwed($termAmountOwed);
    }

    public function getTermAmountOwed()
    {
        $this->__load();
        return parent::getTermAmountOwed();
    }

    public function setAnnualAmountPaid($annualAmountPaid)
    {
        $this->__load();
        return parent::setAnnualAmountPaid($annualAmountPaid);
    }

    public function getAnnualAmountPaid()
    {
        $this->__load();
        return parent::getAnnualAmountPaid();
    }

    public function setAnnualAmountOwed($annualAmountOwed)
    {
        $this->__load();
        return parent::setAnnualAmountOwed($annualAmountOwed);
    }

    public function getAnnualAmountOwed()
    {
        $this->__load();
        return parent::getAnnualAmountOwed();
    }

    public function setDateCreated($dateCreated)
    {
        $this->__load();
        return parent::setDateCreated($dateCreated);
    }

    public function getDateCreated()
    {
        $this->__load();
        return parent::getDateCreated();
    }

    public function setDateLastModified($dateLastModified)
    {
        $this->__load();
        return parent::setDateLastModified($dateLastModified);
    }

    public function getDateLastModified()
    {
        $this->__load();
        return parent::getDateLastModified();
    }

    public function setIsValid($isValid)
    {
        $this->__load();
        return parent::setIsValid($isValid);
    }

    public function getIsValid()
    {
        $this->__load();
        return parent::getIsValid();
    }

    public function setStudent(\Entities\Student $student = NULL)
    {
        $this->__load();
        return parent::setStudent($student);
    }

    public function getStudent()
    {
        $this->__load();
        return parent::getStudent();
    }

    public function setClassInstance(\Entities\ClassInstance $classInstance = NULL)
    {
        $this->__load();
        return parent::setClassInstance($classInstance);
    }

    public function getClassInstance()
    {
        $this->__load();
        return parent::getClassInstance();
    }

    public function setTerm(\Entities\Term $term = NULL)
    {
        $this->__load();
        return parent::setTerm($term);
    }

    public function getTerm()
    {
        $this->__load();
        return parent::getTerm();
    }

    public function setOtherTermPayments($otherTermPayments)
    {
        $this->__load();
        return parent::setOtherTermPayments($otherTermPayments);
    }

    public function getOtherTermPayments()
    {
        $this->__load();
        return parent::getOtherTermPayments();
    }

    public function setOtherAnnualPayments($otherAnnualPayments)
    {
        $this->__load();
        return parent::setOtherAnnualPayments($otherAnnualPayments);
    }

    public function getOtherAnnualPayments()
    {
        $this->__load();
        return parent::getOtherAnnualPayments();
    }

    public function setCompulsaryAmountPaid($compulsaryAmountPaid)
    {
        $this->__load();
        return parent::setCompulsaryAmountPaid($compulsaryAmountPaid);
    }

    public function getCompulsaryAmountPaid()
    {
        $this->__load();
        return parent::getCompulsaryAmountPaid();
    }

    public function setCompulsaryAmountOwed($compulsaryAmountOwed)
    {
        $this->__load();
        return parent::setCompulsaryAmountOwed($compulsaryAmountOwed);
    }

    public function getCompulsaryAmountOwed()
    {
        $this->__load();
        return parent::getCompulsaryAmountOwed();
    }

    public function setOtherAmountPaid($otherAmountPaid)
    {
        $this->__load();
        return parent::setOtherAmountPaid($otherAmountPaid);
    }

    public function getOtherAmountPaid()
    {
        $this->__load();
        return parent::getOtherAmountPaid();
    }

    public function setOtherAmountOwed($otherAmountOwed)
    {
        $this->__load();
        return parent::setOtherAmountOwed($otherAmountOwed);
    }

    public function getOtherAmountOwed()
    {
        $this->__load();
        return parent::getOtherAmountOwed();
    }

    public function setFeeFrequencyType(\Entities\FeeFrequencyType $feeFrequencyType = NULL)
    {
        $this->__load();
        return parent::setFeeFrequencyType($feeFrequencyType);
    }

    public function getFeeFrequencyType()
    {
        $this->__load();
        return parent::getFeeFrequencyType();
    }

    public function setTermFeesSummaryStatus(\Entities\TermFeesSummaryStatus $termFeesSummaryStatus = NULL)
    {
        $this->__load();
        return parent::setTermFeesSummaryStatus($termFeesSummaryStatus);
    }

    public function getTermFeesSummaryStatus()
    {
        $this->__load();
        return parent::getTermFeesSummaryStatus();
    }

    public function setFeesSummaryStatus(\Entities\FeesSummaryStatus $feesSummaryStatus = NULL)
    {
        $this->__load();
        return parent::setFeesSummaryStatus($feesSummaryStatus);
    }

    public function getFeesSummaryStatus()
    {
        $this->__load();
        return parent::getFeesSummaryStatus();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'compulsary_amount_paid', 'compulsary_amount_owed', 'other_amount_paid', 'other_amount_owed', 'date_created', 'date_last_modified', 'is_valid', 'student', 'class_instance', 'term', 'fee_frequency_type', 'fees_summary_status');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}