<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class StudentInventoryRequirement extends \Entities\StudentInventoryRequirement implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNumberBroughtByStudent($numberBroughtByStudent)
    {
        $this->__load();
        return parent::setNumberBroughtByStudent($numberBroughtByStudent);
    }

    public function getNumberBroughtByStudent()
    {
        $this->__load();
        return parent::getNumberBroughtByStudent();
    }

    public function setNumberBoughtBySchool($numberBoughtBySchool)
    {
        $this->__load();
        return parent::setNumberBoughtBySchool($numberBoughtBySchool);
    }

    public function getNumberBoughtBySchool()
    {
        $this->__load();
        return parent::getNumberBoughtBySchool();
    }

    public function setDateCreated($dateCreated)
    {
        $this->__load();
        return parent::setDateCreated($dateCreated);
    }

    public function getDateCreated()
    {
        $this->__load();
        return parent::getDateCreated();
    }

    public function setDateLastModified($dateLastModified)
    {
        $this->__load();
        return parent::setDateLastModified($dateLastModified);
    }

    public function getDateLastModified()
    {
        $this->__load();
        return parent::getDateLastModified();
    }

    public function setIsValid($isValid)
    {
        $this->__load();
        return parent::setIsValid($isValid);
    }

    public function getIsValid()
    {
        $this->__load();
        return parent::getIsValid();
    }

    public function setStudent(\Entities\Student $student = NULL)
    {
        $this->__load();
        return parent::setStudent($student);
    }

    public function getStudent()
    {
        $this->__load();
        return parent::getStudent();
    }

    public function setClassInstance(\Entities\ClassInstance $classInstance = NULL)
    {
        $this->__load();
        return parent::setClassInstance($classInstance);
    }

    public function getClassInstance()
    {
        $this->__load();
        return parent::getClassInstance();
    }

    public function setTerm(\Entities\Term $term = NULL)
    {
        $this->__load();
        return parent::setTerm($term);
    }

    public function getTerm()
    {
        $this->__load();
        return parent::getTerm();
    }

    public function setStudentRequiredItem(\Entities\StudentRequiredItem $studentRequiredItem = NULL)
    {
        $this->__load();
        return parent::setStudentRequiredItem($studentRequiredItem);
    }

    public function getStudentRequiredItem()
    {
        $this->__load();
        return parent::getStudentRequiredItem();
    }

    public function setTransaction(\Entities\Transaction $transaction = NULL)
    {
        $this->__load();
        return parent::setTransaction($transaction);
    }

    public function getTransaction()
    {
        $this->__load();
        return parent::getTransaction();
    }

    public function setWasPaid($wasPaid)
    {
        $this->__load();
        return parent::setWasPaid($wasPaid);
    }

    public function getWasPaid()
    {
        $this->__load();
        return parent::getWasPaid();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'number_brought_by_student', 'number_bought_by_school', 'was_paid', 'date_created', 'date_last_modified', 'is_valid', 'student', 'class_instance', 'term', 'student_required_item', 'transaction');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}