<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Debt extends \Entities\Debt implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setTotalDebtAmount($totalDebtAmount)
    {
        $this->__load();
        return parent::setTotalDebtAmount($totalDebtAmount);
    }

    public function getTotalDebtAmount()
    {
        $this->__load();
        return parent::getTotalDebtAmount();
    }

    public function setPaidAmount($paidAmount)
    {
        $this->__load();
        return parent::setPaidAmount($paidAmount);
    }

    public function getPaidAmount()
    {
        $this->__load();
        return parent::getPaidAmount();
    }

    public function setDateCreated($dateCreated)
    {
        $this->__load();
        return parent::setDateCreated($dateCreated);
    }

    public function getDateCreated()
    {
        $this->__load();
        return parent::getDateCreated();
    }

    public function setDateLastModified($dateLastModified)
    {
        $this->__load();
        return parent::setDateLastModified($dateLastModified);
    }

    public function getDateLastModified()
    {
        $this->__load();
        return parent::getDateLastModified();
    }

    public function setIsValid($isValid)
    {
        $this->__load();
        return parent::setIsValid($isValid);
    }

    public function getIsValid()
    {
        $this->__load();
        return parent::getIsValid();
    }

    public function setAccount(\Entities\Account $account = NULL)
    {
        $this->__load();
        return parent::setAccount($account);
    }

    public function getAccount()
    {
        $this->__load();
        return parent::getAccount();
    }

    public function setClassInstance(\Entities\ClassInstance $classInstance = NULL)
    {
        $this->__load();
        return parent::setClassInstance($classInstance);
    }

    public function getClassInstance()
    {
        $this->__load();
        return parent::getClassInstance();
    }

    public function setTermIncurred(\Entities\Term $termIncurred = NULL)
    {
        $this->__load();
        return parent::setTermIncurred($termIncurred);
    }

    public function getTermIncurred()
    {
        $this->__load();
        return parent::getTermIncurred();
    }

    public function setTermCleared(\Entities\Term $termCleared = NULL)
    {
        $this->__load();
        return parent::setTermCleared($termCleared);
    }

    public function getTermCleared()
    {
        $this->__load();
        return parent::getTermCleared();
    }

    public function setDebtType(\Entities\DebtType $debtType = NULL)
    {
        $this->__load();
        return parent::setDebtType($debtType);
    }

    public function getDebtType()
    {
        $this->__load();
        return parent::getDebtType();
    }

    public function setDebtStatus(\Entities\DebtStatus $debtStatus = NULL)
    {
        $this->__load();
        return parent::setDebtStatus($debtStatus);
    }

    public function getDebtStatus()
    {
        $this->__load();
        return parent::getDebtStatus();
    }

    public function setNarrative($narrative)
    {
        $this->__load();
        return parent::setNarrative($narrative);
    }

    public function getNarrative()
    {
        $this->__load();
        return parent::getNarrative();
    }

    public function setFeeFrequencyType(\Entities\FeeFrequencyType $feeFrequencyType = NULL)
    {
        $this->__load();
        return parent::setFeeFrequencyType($feeFrequencyType);
    }

    public function getFeeFrequencyType()
    {
        $this->__load();
        return parent::getFeeFrequencyType();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'total_debt_amount', 'paid_amount', 'narrative', 'date_created', 'date_last_modified', 'is_valid', 'account', 'class_instance', 'term_incurred', 'term_cleared', 'debt_type', 'debt_status', 'fee_frequency_type');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}