<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ExamResultsSummary extends \Entities\ExamResultsSummary implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setTotalMarks($totalMarks)
    {
        $this->__load();
        return parent::setTotalMarks($totalMarks);
    }

    public function getTotalMarks()
    {
        $this->__load();
        return parent::getTotalMarks();
    }

    public function setTotalAggregates($totalAggregates)
    {
        $this->__load();
        return parent::setTotalAggregates($totalAggregates);
    }

    public function getTotalAggregates()
    {
        $this->__load();
        return parent::getTotalAggregates();
    }

    public function setPosition($position)
    {
        $this->__load();
        return parent::setPosition($position);
    }

    public function getPosition()
    {
        $this->__load();
        return parent::getPosition();
    }

    public function setDivision($division)
    {
        $this->__load();
        return parent::setDivision($division);
    }

    public function getDivision()
    {
        $this->__load();
        return parent::getDivision();
    }

    public function setGrade($grade)
    {
        $this->__load();
        return parent::setGrade($grade);
    }

    public function getGrade()
    {
        $this->__load();
        return parent::getGrade();
    }

    public function setRemarks($remarks)
    {
        $this->__load();
        return parent::setRemarks($remarks);
    }

    public function getRemarks()
    {
        $this->__load();
        return parent::getRemarks();
    }

    public function setDateCreated($dateCreated)
    {
        $this->__load();
        return parent::setDateCreated($dateCreated);
    }

    public function getDateCreated()
    {
        $this->__load();
        return parent::getDateCreated();
    }

    public function setDateLastModified($dateLastModified)
    {
        $this->__load();
        return parent::setDateLastModified($dateLastModified);
    }

    public function getDateLastModified()
    {
        $this->__load();
        return parent::getDateLastModified();
    }

    public function setIsValid($isValid)
    {
        $this->__load();
        return parent::setIsValid($isValid);
    }

    public function getIsValid()
    {
        $this->__load();
        return parent::getIsValid();
    }

    public function setStudent(\Entities\Student $student = NULL)
    {
        $this->__load();
        return parent::setStudent($student);
    }

    public function getStudent()
    {
        $this->__load();
        return parent::getStudent();
    }

    public function setClassInstance(\Entities\ClassInstance $classInstance = NULL)
    {
        $this->__load();
        return parent::setClassInstance($classInstance);
    }

    public function getClassInstance()
    {
        $this->__load();
        return parent::getClassInstance();
    }

    public function setTerm(\Entities\Term $term = NULL)
    {
        $this->__load();
        return parent::setTerm($term);
    }

    public function getTerm()
    {
        $this->__load();
        return parent::getTerm();
    }

    public function setExam(\Entities\Exam $exam = NULL)
    {
        $this->__load();
        return parent::setExam($exam);
    }

    public function getExam()
    {
        $this->__load();
        return parent::getExam();
    }

    public function setExamResultsStatus(\Entities\ExamResultsStatus $examResultsStatus = NULL)
    {
        $this->__load();
        return parent::setExamResultsStatus($examResultsStatus);
    }

    public function getExamResultsStatus()
    {
        $this->__load();
        return parent::getExamResultsStatus();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'total_marks', 'total_aggregates', 'position', 'division', 'grade', 'remarks', 'date_created', 'date_last_modified', 'is_valid', 'student', 'class_instance', 'term', 'exam', 'exam_results_status');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}